### ISSUE TITLE
Script runs, but shows nothing in Azure Portal

### ISSUE THREAD

**Issue by mrichman** [kevinhillinger/webjob-deploy-with-kudu#1]
After running `Login-AzureRmAccount` and `Select-AzureRmSubscription`, I ran the script as follows:

```
C:\tfs\Ecosys\SCM\Azure\Deploy-WebJob.ps1 -WebAppName 900003webjobs -WebAppResourceGroupName 900003-prod -WebJobName 'CMCMessageProcessingService' -WebJobType scheduled -WebJobPath "C:\WebJobs\CMCMessageProcessingService"
Creating WebJob package
Deploying WebJob to 900003webjobs

CMCMessageProcessingService Deployment complete.
```
Nothing shows up in Azure Portal:

![image](https://user-images.githubusercontent.com/11228/33626806-aaf9296e-d9c9-11e7-95bd-a0fc265a548e.png)

But I do see the files deployed:

![image](https://user-images.githubusercontent.com/11228/33626892-e041e2be-d9c9-11e7-8f10-e30985477d4a.png)

**Comment by kevinhillinger** [comment]
@mrichman I wasn't able to duplicate the issue. I created a new web app, then executed the Deploy-WebJob against the web app. The WebJob did end up displaying in the portal.

I added to the readme that recommends placing the script `outside` the folder you'll use as your webjob. I noticed in the screenshot that it seems the script was placed directly, making the webjob path the same as the script location, which shouldn't be done.

**Comment by mrichman** [comment]
@kevinhillinger My script is indeed **outside** the folder structure of my web job. I just created a fresh app service, and ran it again, using your latest [commit](https://github.com/kevinhillinger/webjob-deploy-with-kudu/commit/ceb4c0b0070ca9f951d1d1eb372656feee9d399e). Still nothing in Azure Portal. Can I zip up my bits and send them to you?

**Comment by kevinhillinger** [comment]
@mrichman looking more closely at your script params, I see you're setting the type to "scheduled". There are only two WebJob types: triggered, and continuous. This is why the job is not being picked up. 

A scheduled webjob is just a triggered job via a schedule. I've updated the README with further info on this.

**Comment by mrichman** [comment]
@kevinhillinger from your current README: `-WebJobType '< triggered|scheduled >'`

I tried specifying `-WebJobType continuous` and `-WebJobType triggered` but got the same results (nothing in Azure Portal). I also see nothing in the App Service's Activity Log - should I?
